// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package gosnowflake

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson90b16446DecodeGithubComObserveincGosnowflake(in *jlexer.Lexer, out *execResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data":
			easyjson90b16446DecodeGithubComObserveincGosnowflake1(in, &out.Data)
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake(out *jwriter.Writer, in execResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix[1:])
		easyjson90b16446EncodeGithubComObserveincGosnowflake1(out, in.Data)
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix)
		out.Bool(bool(in.Success))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v execResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson90b16446EncodeGithubComObserveincGosnowflake(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v execResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson90b16446EncodeGithubComObserveincGosnowflake(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *execResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson90b16446DecodeGithubComObserveincGosnowflake(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *execResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson90b16446DecodeGithubComObserveincGosnowflake(l, v)
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake1(in *jlexer.Lexer, out *execResponseData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "parameters":
			if in.IsNull() {
				in.Skip()
				out.Parameters = nil
			} else {
				in.Delim('[')
				if out.Parameters == nil {
					if !in.IsDelim(']') {
						out.Parameters = make([]nameValueParameter, 0, 2)
					} else {
						out.Parameters = []nameValueParameter{}
					}
				} else {
					out.Parameters = (out.Parameters)[:0]
				}
				for !in.IsDelim(']') {
					var v1 nameValueParameter
					easyjson90b16446DecodeGithubComObserveincGosnowflake2(in, &v1)
					out.Parameters = append(out.Parameters, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "rowtype":
			if in.IsNull() {
				in.Skip()
				out.RowType = nil
			} else {
				in.Delim('[')
				if out.RowType == nil {
					if !in.IsDelim(']') {
						out.RowType = make([]execResponseRowType, 0, 0)
					} else {
						out.RowType = []execResponseRowType{}
					}
				} else {
					out.RowType = (out.RowType)[:0]
				}
				for !in.IsDelim(']') {
					var v2 execResponseRowType
					easyjson90b16446DecodeGithubComObserveincGosnowflake3(in, &v2)
					out.RowType = append(out.RowType, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "rowset":
			if in.IsNull() {
				in.Skip()
				out.RowSet = nil
			} else {
				in.Delim('[')
				if out.RowSet == nil {
					if !in.IsDelim(']') {
						out.RowSet = make([][]*string, 0, 2)
					} else {
						out.RowSet = [][]*string{}
					}
				} else {
					out.RowSet = (out.RowSet)[:0]
				}
				for !in.IsDelim(']') {
					var v3 []*string
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						in.Delim('[')
						if v3 == nil {
							if !in.IsDelim(']') {
								v3 = make([]*string, 0, 8)
							} else {
								v3 = []*string{}
							}
						} else {
							v3 = (v3)[:0]
						}
						for !in.IsDelim(']') {
							var v4 *string
							if in.IsNull() {
								in.Skip()
								v4 = nil
							} else {
								if v4 == nil {
									v4 = new(string)
								}
								if in.IsNull() {
									in.Skip()
								} else {
									*v4 = string(in.String())
								}
							}
							v3 = append(v3, v4)
							in.WantComma()
						}
						in.Delim(']')
					}
					out.RowSet = append(out.RowSet, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "rowsetbase64":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RowSetBase64 = string(in.String())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int64(in.Int64())
			}
		case "returned":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Returned = int64(in.Int64())
			}
		case "queryId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryID = string(in.String())
			}
		case "sqlState":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SQLState = string(in.String())
			}
		case "databaseProvider":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DatabaseProvider = string(in.String())
			}
		case "finalDatabaseName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FinalDatabaseName = string(in.String())
			}
		case "finalSchemaName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FinalSchemaName = string(in.String())
			}
		case "finalWarehouseName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FinalWarehouseName = string(in.String())
			}
		case "finalRoleName":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FinalRoleName = string(in.String())
			}
		case "numberOfBinds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NumberOfBinds = int(in.Int())
			}
		case "statementTypeId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StatementTypeID = int64(in.Int64())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int64(in.Int64())
			}
		case "chunks":
			if in.IsNull() {
				in.Skip()
				out.Chunks = nil
			} else {
				in.Delim('[')
				if out.Chunks == nil {
					if !in.IsDelim(']') {
						out.Chunks = make([]execResponseChunk, 0, 1)
					} else {
						out.Chunks = []execResponseChunk{}
					}
				} else {
					out.Chunks = (out.Chunks)[:0]
				}
				for !in.IsDelim(']') {
					var v5 execResponseChunk
					easyjson90b16446DecodeGithubComObserveincGosnowflake4(in, &v5)
					out.Chunks = append(out.Chunks, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "qrmk":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Qrmk = string(in.String())
			}
		case "chunkHeaders":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.ChunkHeaders = make(map[string]string)
				} else {
					out.ChunkHeaders = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v6 string
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = string(in.String())
					}
					(out.ChunkHeaders)[key] = v6
					in.WantComma()
				}
				in.Delim('}')
			}
		case "getResultUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GetResultURL = string(in.String())
			}
		case "progressDesc":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProgressDesc = string(in.String())
			}
		case "queryAbortsAfterSecs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryAbortTimeout = time.Duration(in.Int64())
			}
		case "resultIds":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ResultIDs = string(in.String())
			}
		case "resultTypes":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ResultTypes = string(in.String())
			}
		case "queryResultFormat":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryResultFormat = string(in.String())
			}
		case "asyncResult":
			if in.IsNull() {
				in.Skip()
				out.AsyncResult = nil
			} else {
				if out.AsyncResult == nil {
					out.AsyncResult = new(snowflakeResult)
				}
				easyjson90b16446DecodeGithubComObserveincGosnowflake5(in, out.AsyncResult)
			}
		case "asyncRows":
			if in.IsNull() {
				in.Skip()
				out.AsyncRows = nil
			} else {
				if out.AsyncRows == nil {
					out.AsyncRows = new(snowflakeRows)
				}
				easyjson90b16446DecodeGithubComObserveincGosnowflake6(in, out.AsyncRows)
			}
		case "uploadInfo":
			easyjson90b16446DecodeGithubComObserveincGosnowflake7(in, &out.UploadInfo)
		case "localLocation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LocalLocation = string(in.String())
			}
		case "src_locations":
			if in.IsNull() {
				in.Skip()
				out.SrcLocations = nil
			} else {
				in.Delim('[')
				if out.SrcLocations == nil {
					if !in.IsDelim(']') {
						out.SrcLocations = make([]string, 0, 4)
					} else {
						out.SrcLocations = []string{}
					}
				} else {
					out.SrcLocations = (out.SrcLocations)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.SrcLocations = append(out.SrcLocations, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "parallel":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Parallel = int64(in.Int64())
			}
		case "threshold":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Threshold = int64(in.Int64())
			}
		case "autoCompress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AutoCompress = bool(in.Bool())
			}
		case "overwrite":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Overwrite = bool(in.Bool())
			}
		case "sourceCompression":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceCompression = string(in.String())
			}
		case "clientShowEncryptionParameter":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ShowEncryptionParameter = bool(in.Bool())
			}
		case "encryptionMaterial":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.EncryptionMaterial).UnmarshalJSON(data))
				}
			}
		case "presignedUrls":
			if in.IsNull() {
				in.Skip()
				out.PresignedURLs = nil
			} else {
				in.Delim('[')
				if out.PresignedURLs == nil {
					if !in.IsDelim(']') {
						out.PresignedURLs = make([]string, 0, 4)
					} else {
						out.PresignedURLs = []string{}
					}
				} else {
					out.PresignedURLs = (out.PresignedURLs)[:0]
				}
				for !in.IsDelim(']') {
					var v8 string
					if in.IsNull() {
						in.Skip()
					} else {
						v8 = string(in.String())
					}
					out.PresignedURLs = append(out.PresignedURLs, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "stageInfo":
			easyjson90b16446DecodeGithubComObserveincGosnowflake7(in, &out.StageInfo)
		case "command":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Command = string(in.String())
			}
		case "kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = string(in.String())
			}
		case "operation":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Operation = string(in.String())
			}
		case "queryContext":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.QueryContext).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake1(out *jwriter.Writer, in execResponseData) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Parameters) != 0 {
		const prefix string = ",\"parameters\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v9, v10 := range in.Parameters {
				if v9 > 0 {
					out.RawByte(',')
				}
				easyjson90b16446EncodeGithubComObserveincGosnowflake2(out, v10)
			}
			out.RawByte(']')
		}
	}
	if len(in.RowType) != 0 {
		const prefix string = ",\"rowtype\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.RowType {
				if v11 > 0 {
					out.RawByte(',')
				}
				easyjson90b16446EncodeGithubComObserveincGosnowflake3(out, v12)
			}
			out.RawByte(']')
		}
	}
	if len(in.RowSet) != 0 {
		const prefix string = ",\"rowset\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v13, v14 := range in.RowSet {
				if v13 > 0 {
					out.RawByte(',')
				}
				if v14 == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v15, v16 := range v14 {
						if v15 > 0 {
							out.RawByte(',')
						}
						if v16 == nil {
							out.RawString("null")
						} else {
							out.String(string(*v16))
						}
					}
					out.RawByte(']')
				}
			}
			out.RawByte(']')
		}
	}
	if in.RowSetBase64 != "" {
		const prefix string = ",\"rowsetbase64\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.RowSetBase64))
	}
	if in.Total != 0 {
		const prefix string = ",\"total\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Total))
	}
	if in.Returned != 0 {
		const prefix string = ",\"returned\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Returned))
	}
	if in.QueryID != "" {
		const prefix string = ",\"queryId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.QueryID))
	}
	if in.SQLState != "" {
		const prefix string = ",\"sqlState\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SQLState))
	}
	if in.DatabaseProvider != "" {
		const prefix string = ",\"databaseProvider\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.DatabaseProvider))
	}
	if in.FinalDatabaseName != "" {
		const prefix string = ",\"finalDatabaseName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FinalDatabaseName))
	}
	if in.FinalSchemaName != "" {
		const prefix string = ",\"finalSchemaName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FinalSchemaName))
	}
	if in.FinalWarehouseName != "" {
		const prefix string = ",\"finalWarehouseName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FinalWarehouseName))
	}
	if in.FinalRoleName != "" {
		const prefix string = ",\"finalRoleName\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.FinalRoleName))
	}
	if in.NumberOfBinds != 0 {
		const prefix string = ",\"numberOfBinds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.NumberOfBinds))
	}
	if in.StatementTypeID != 0 {
		const prefix string = ",\"statementTypeId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.StatementTypeID))
	}
	if in.Version != 0 {
		const prefix string = ",\"version\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Version))
	}
	if len(in.Chunks) != 0 {
		const prefix string = ",\"chunks\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v17, v18 := range in.Chunks {
				if v17 > 0 {
					out.RawByte(',')
				}
				easyjson90b16446EncodeGithubComObserveincGosnowflake4(out, v18)
			}
			out.RawByte(']')
		}
	}
	if in.Qrmk != "" {
		const prefix string = ",\"qrmk\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Qrmk))
	}
	if len(in.ChunkHeaders) != 0 {
		const prefix string = ",\"chunkHeaders\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('{')
			v19First := true
			for v19Name, v19Value := range in.ChunkHeaders {
				if v19First {
					v19First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v19Name))
				out.RawByte(':')
				out.String(string(v19Value))
			}
			out.RawByte('}')
		}
	}
	if in.GetResultURL != "" {
		const prefix string = ",\"getResultUrl\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.GetResultURL))
	}
	if in.ProgressDesc != "" {
		const prefix string = ",\"progressDesc\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ProgressDesc))
	}
	if in.QueryAbortTimeout != 0 {
		const prefix string = ",\"queryAbortsAfterSecs\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.QueryAbortTimeout))
	}
	if in.ResultIDs != "" {
		const prefix string = ",\"resultIds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ResultIDs))
	}
	if in.ResultTypes != "" {
		const prefix string = ",\"resultTypes\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ResultTypes))
	}
	if in.QueryResultFormat != "" {
		const prefix string = ",\"queryResultFormat\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.QueryResultFormat))
	}
	if in.AsyncResult != nil {
		const prefix string = ",\"asyncResult\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson90b16446EncodeGithubComObserveincGosnowflake5(out, *in.AsyncResult)
	}
	if in.AsyncRows != nil {
		const prefix string = ",\"asyncRows\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson90b16446EncodeGithubComObserveincGosnowflake6(out, *in.AsyncRows)
	}
	if true {
		const prefix string = ",\"uploadInfo\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson90b16446EncodeGithubComObserveincGosnowflake7(out, in.UploadInfo)
	}
	if in.LocalLocation != "" {
		const prefix string = ",\"localLocation\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LocalLocation))
	}
	if len(in.SrcLocations) != 0 {
		const prefix string = ",\"src_locations\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v20, v21 := range in.SrcLocations {
				if v20 > 0 {
					out.RawByte(',')
				}
				out.String(string(v21))
			}
			out.RawByte(']')
		}
	}
	if in.Parallel != 0 {
		const prefix string = ",\"parallel\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Parallel))
	}
	if in.Threshold != 0 {
		const prefix string = ",\"threshold\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.Threshold))
	}
	if in.AutoCompress {
		const prefix string = ",\"autoCompress\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.AutoCompress))
	}
	if in.Overwrite {
		const prefix string = ",\"overwrite\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Overwrite))
	}
	if in.SourceCompression != "" {
		const prefix string = ",\"sourceCompression\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.SourceCompression))
	}
	if in.ShowEncryptionParameter {
		const prefix string = ",\"clientShowEncryptionParameter\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.ShowEncryptionParameter))
	}
	if true {
		const prefix string = ",\"encryptionMaterial\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson90b16446EncodeGithubComObserveincGosnowflake8(out, in.EncryptionMaterial)
	}
	if len(in.PresignedURLs) != 0 {
		const prefix string = ",\"presignedUrls\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v22, v23 := range in.PresignedURLs {
				if v22 > 0 {
					out.RawByte(',')
				}
				out.String(string(v23))
			}
			out.RawByte(']')
		}
	}
	if true {
		const prefix string = ",\"stageInfo\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson90b16446EncodeGithubComObserveincGosnowflake7(out, in.StageInfo)
	}
	if in.Command != "" {
		const prefix string = ",\"command\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Command))
	}
	if in.Kind != "" {
		const prefix string = ",\"kind\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Kind))
	}
	if in.Operation != "" {
		const prefix string = ",\"operation\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Operation))
	}
	if len(in.QueryContext) != 0 {
		const prefix string = ",\"queryContext\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((in.QueryContext).MarshalJSON())
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake8(in *jlexer.Lexer, out *encryptionWrapper) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "encryptionMaterials":
			if in.IsNull() {
				in.Skip()
				out.EncryptionMaterials = nil
			} else {
				in.Delim('[')
				if out.EncryptionMaterials == nil {
					if !in.IsDelim(']') {
						out.EncryptionMaterials = make([]snowflakeFileEncryption, 0, 1)
					} else {
						out.EncryptionMaterials = []snowflakeFileEncryption{}
					}
				} else {
					out.EncryptionMaterials = (out.EncryptionMaterials)[:0]
				}
				for !in.IsDelim(']') {
					var v24 snowflakeFileEncryption
					easyjson90b16446DecodeGithubComObserveincGosnowflake9(in, &v24)
					out.EncryptionMaterials = append(out.EncryptionMaterials, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "queryStageMasterKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryStageMasterKey = string(in.String())
			}
		case "queryId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryID = string(in.String())
			}
		case "smkId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SMKID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake8(out *jwriter.Writer, in encryptionWrapper) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"encryptionMaterials\":"
		out.RawString(prefix[1:])
		if in.EncryptionMaterials == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v25, v26 := range in.EncryptionMaterials {
				if v25 > 0 {
					out.RawByte(',')
				}
				easyjson90b16446EncodeGithubComObserveincGosnowflake9(out, v26)
			}
			out.RawByte(']')
		}
	}
	if in.QueryStageMasterKey != "" {
		const prefix string = ",\"queryStageMasterKey\":"
		out.RawString(prefix)
		out.String(string(in.QueryStageMasterKey))
	}
	if in.QueryID != "" {
		const prefix string = ",\"queryId\":"
		out.RawString(prefix)
		out.String(string(in.QueryID))
	}
	if in.SMKID != 0 {
		const prefix string = ",\"smkId\":"
		out.RawString(prefix)
		out.Int64(int64(in.SMKID))
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake9(in *jlexer.Lexer, out *snowflakeFileEncryption) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "queryStageMasterKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryStageMasterKey = string(in.String())
			}
		case "queryId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.QueryID = string(in.String())
			}
		case "smkId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SMKID = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake9(out *jwriter.Writer, in snowflakeFileEncryption) {
	out.RawByte('{')
	first := true
	_ = first
	if in.QueryStageMasterKey != "" {
		const prefix string = ",\"queryStageMasterKey\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.QueryStageMasterKey))
	}
	if in.QueryID != "" {
		const prefix string = ",\"queryId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.QueryID))
	}
	if in.SMKID != 0 {
		const prefix string = ",\"smkId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int64(int64(in.SMKID))
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake7(in *jlexer.Lexer, out *execResponseStageInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "locationType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LocationType = string(in.String())
			}
		case "location":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Location = string(in.String())
			}
		case "path":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Path = string(in.String())
			}
		case "region":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Region = string(in.String())
			}
		case "storageAccount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.StorageAccount = string(in.String())
			}
		case "isClientSideEncrypted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsClientSideEncrypted = bool(in.Bool())
			}
		case "creds":
			easyjson90b16446DecodeGithubComObserveincGosnowflake10(in, &out.Creds)
		case "presignedUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PresignedURL = string(in.String())
			}
		case "endPoint":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EndPoint = string(in.String())
			}
		case "useS3RegionalUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UseS3RegionalURL = bool(in.Bool())
			}
		case "useRegionalUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UseRegionalURL = bool(in.Bool())
			}
		case "useVirtualUrl":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UseVirtualURL = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake7(out *jwriter.Writer, in execResponseStageInfo) {
	out.RawByte('{')
	first := true
	_ = first
	if in.LocationType != "" {
		const prefix string = ",\"locationType\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.LocationType))
	}
	if in.Location != "" {
		const prefix string = ",\"location\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Location))
	}
	if in.Path != "" {
		const prefix string = ",\"path\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Path))
	}
	if in.Region != "" {
		const prefix string = ",\"region\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Region))
	}
	if in.StorageAccount != "" {
		const prefix string = ",\"storageAccount\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.StorageAccount))
	}
	if in.IsClientSideEncrypted {
		const prefix string = ",\"isClientSideEncrypted\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.IsClientSideEncrypted))
	}
	if true {
		const prefix string = ",\"creds\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjson90b16446EncodeGithubComObserveincGosnowflake10(out, in.Creds)
	}
	if in.PresignedURL != "" {
		const prefix string = ",\"presignedUrl\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.PresignedURL))
	}
	if in.EndPoint != "" {
		const prefix string = ",\"endPoint\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.EndPoint))
	}
	if in.UseS3RegionalURL {
		const prefix string = ",\"useS3RegionalUrl\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.UseS3RegionalURL))
	}
	if in.UseRegionalURL {
		const prefix string = ",\"useRegionalUrl\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.UseRegionalURL))
	}
	if in.UseVirtualURL {
		const prefix string = ",\"useVirtualUrl\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.UseVirtualURL))
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake10(in *jlexer.Lexer, out *execResponseCredentials) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "AWS_KEY_ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwsKeyID = string(in.String())
			}
		case "AWS_SECRET_KEY":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwsSecretKey = string(in.String())
			}
		case "AWS_TOKEN":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwsToken = string(in.String())
			}
		case "AWS_ID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwsID = string(in.String())
			}
		case "AWS_KEY":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwsKey = string(in.String())
			}
		case "AZURE_SAS_TOKEN":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AzureSasToken = string(in.String())
			}
		case "GCS_ACCESS_TOKEN":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GcsAccessToken = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake10(out *jwriter.Writer, in execResponseCredentials) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AwsKeyID != "" {
		const prefix string = ",\"AWS_KEY_ID\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.AwsKeyID))
	}
	if in.AwsSecretKey != "" {
		const prefix string = ",\"AWS_SECRET_KEY\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AwsSecretKey))
	}
	if in.AwsToken != "" {
		const prefix string = ",\"AWS_TOKEN\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AwsToken))
	}
	if in.AwsID != "" {
		const prefix string = ",\"AWS_ID\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AwsID))
	}
	if in.AwsKey != "" {
		const prefix string = ",\"AWS_KEY\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AwsKey))
	}
	if in.AzureSasToken != "" {
		const prefix string = ",\"AZURE_SAS_TOKEN\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AzureSasToken))
	}
	if in.GcsAccessToken != "" {
		const prefix string = ",\"GCS_ACCESS_TOKEN\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.GcsAccessToken))
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake6(in *jlexer.Lexer, out *snowflakeRows) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake6(out *jwriter.Writer, in snowflakeRows) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake5(in *jlexer.Lexer, out *snowflakeResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake5(out *jwriter.Writer, in snowflakeResult) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake4(in *jlexer.Lexer, out *execResponseChunk) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		case "rowCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RowCount = int(in.Int())
			}
		case "uncompressedSize":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UncompressedSize = int64(in.Int64())
			}
		case "compressedSize":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CompressedSize = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake4(out *jwriter.Writer, in execResponseChunk) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"rowCount\":"
		out.RawString(prefix)
		out.Int(int(in.RowCount))
	}
	{
		const prefix string = ",\"uncompressedSize\":"
		out.RawString(prefix)
		out.Int64(int64(in.UncompressedSize))
	}
	{
		const prefix string = ",\"compressedSize\":"
		out.RawString(prefix)
		out.Int64(int64(in.CompressedSize))
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake3(in *jlexer.Lexer, out *execResponseRowType) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "fields":
			if in.IsNull() {
				in.Skip()
				out.Fields = nil
			} else {
				in.Delim('[')
				if out.Fields == nil {
					if !in.IsDelim(']') {
						out.Fields = make([]fieldMetadata, 0, 0)
					} else {
						out.Fields = []fieldMetadata{}
					}
				} else {
					out.Fields = (out.Fields)[:0]
				}
				for !in.IsDelim(']') {
					var v27 fieldMetadata
					easyjson90b16446DecodeGithubComObserveincGosnowflake11(in, &v27)
					out.Fields = append(out.Fields, v27)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "byteLength":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ByteLength = int64(in.Int64())
			}
		case "length":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Length = int64(in.Int64())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "precision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Precision = int64(in.Int64())
			}
		case "scale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Scale = int64(in.Int64())
			}
		case "nullable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nullable = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake3(out *jwriter.Writer, in execResponseRowType) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"fields\":"
		out.RawString(prefix)
		if in.Fields == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v28, v29 := range in.Fields {
				if v28 > 0 {
					out.RawByte(',')
				}
				easyjson90b16446EncodeGithubComObserveincGosnowflake11(out, v29)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"byteLength\":"
		out.RawString(prefix)
		out.Int64(int64(in.ByteLength))
	}
	{
		const prefix string = ",\"length\":"
		out.RawString(prefix)
		out.Int64(int64(in.Length))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"precision\":"
		out.RawString(prefix)
		out.Int64(int64(in.Precision))
	}
	{
		const prefix string = ",\"scale\":"
		out.RawString(prefix)
		out.Int64(int64(in.Scale))
	}
	{
		const prefix string = ",\"nullable\":"
		out.RawString(prefix)
		out.Bool(bool(in.Nullable))
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake11(in *jlexer.Lexer, out *fieldMetadata) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "nullable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nullable = bool(in.Bool())
			}
		case "length":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Length = int(in.Int())
			}
		case "scale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Scale = int(in.Int())
			}
		case "precision":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Precision = int(in.Int())
			}
		case "fields":
			if in.IsNull() {
				in.Skip()
				out.Fields = nil
			} else {
				in.Delim('[')
				if out.Fields == nil {
					if !in.IsDelim(']') {
						out.Fields = make([]fieldMetadata, 0, 0)
					} else {
						out.Fields = []fieldMetadata{}
					}
				} else {
					out.Fields = (out.Fields)[:0]
				}
				for !in.IsDelim(']') {
					var v30 fieldMetadata
					easyjson90b16446DecodeGithubComObserveincGosnowflake11(in, &v30)
					out.Fields = append(out.Fields, v30)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake11(out *jwriter.Writer, in fieldMetadata) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != "" {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"nullable\":"
		out.RawString(prefix)
		out.Bool(bool(in.Nullable))
	}
	{
		const prefix string = ",\"length\":"
		out.RawString(prefix)
		out.Int(int(in.Length))
	}
	{
		const prefix string = ",\"scale\":"
		out.RawString(prefix)
		out.Int(int(in.Scale))
	}
	{
		const prefix string = ",\"precision\":"
		out.RawString(prefix)
		out.Int(int(in.Precision))
	}
	if len(in.Fields) != 0 {
		const prefix string = ",\"fields\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v31, v32 := range in.Fields {
				if v31 > 0 {
					out.RawByte(',')
				}
				easyjson90b16446EncodeGithubComObserveincGosnowflake11(out, v32)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson90b16446DecodeGithubComObserveincGosnowflake2(in *jlexer.Lexer, out *nameValueParameter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "value":
			if m, ok := out.Value.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Value.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Value = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson90b16446EncodeGithubComObserveincGosnowflake2(out *jwriter.Writer, in nameValueParameter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		if m, ok := in.Value.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Value.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Value))
		}
	}
	out.RawByte('}')
}
